source :rubygems

gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'bson_ext'
gem 'coffee-script'
gem 'foreman'
gem 'jbuilder'
gem 'mongoid'
gem 'pony'
gem 'rack'
gem 'rake'
gem 'redcarpet'
gem 'resque'
gem 'sass'
gem 'sinatra'
gem 'slim'
gem 'sprockets'
gem 'state_machine'
gem 'uglifier'
gem 'uuid'
gem 'warden'
